version: '2.3'
services:
  # MySQL has been used for evaluation purposes only
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    volumes:
        - ${PWD}/mysql/scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    environment:
      MYSQL_ROOT_PASSWORD: wso2carbon
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pwso2carbon"]
      interval: 5s
      timeout: 60s

  analytics-1:
    container_name: analytics-1
    image: wso2das:3.1.0
    ports:
      - 9763
      - 9443
      - 7711
      - 7611
      - 4000
    healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
        interval: 5s
        timeout: 120s
        start_period: 120s
    volumes:
        - ${PWD}/data-analytics-server/repository/conf/analytics/spark/spark-defaults.conf:/home/wso2carbon/wso2das-3.1.0/repository/conf/analytics/spark/spark-defaults.conf
        - ${PWD}/data-analytics-server/repository/conf/analytics/my-node-id-1.dat:/home/wso2carbon/wso2das-3.1.0/repository/conf/analytics/my-node-id.dat
        - ${PWD}/data-analytics-server/repository/conf/axis2/axis2-1.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/axis2/axis2.xml
        - ${PWD}/data-analytics-server/repository/conf/datasources/analytics-datasources.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/datasources/analytics-datasources.xml
        - ${PWD}/data-analytics-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/datasources/master-datasources.xml
        - ${PWD}/data-analytics-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/tomcat/catalina-server.xml
        - ${PWD}/data-analytics-server/repository/conf/carbon.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/carbon.xml
        - ${PWD}/data-analytics-server/repository/conf/event-processor-1.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/event-processor.xml
        - ${PWD}/data-analytics-server/repository/conf/registry.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/registry.xml
        - ${PWD}/data-analytics-server/repository/conf/user-mgt.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/user-mgt.xml
        - ${PWD}/data-analytics-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2das-3.1.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
    depends_on:
      mysql:
        condition: service_healthy
    links:
        - mysql

  analytics-2:
    container_name: analytics-2
    image: wso2das:3.1.0
    ports:
      - 9763
      - 9443
      - 7711
      - 7611
      - 4000
    healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
        interval: 5s
        timeout: 120s
        start_period: 120s
    volumes:
        - ${PWD}/data-analytics-server/repository/conf/analytics/spark/spark-defaults.conf:/home/wso2carbon/wso2das-3.1.0/repository/conf/analytics/spark/spark-defaults.conf
        - ${PWD}/data-analytics-server/repository/conf/analytics/my-node-id-2.dat:/home/wso2carbon/wso2das-3.1.0/repository/conf/analytics/my-node-id.dat
        - ${PWD}/data-analytics-server/repository/conf/axis2/axis2-2.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/axis2/axis2.xml
        - ${PWD}/data-analytics-server/repository/conf/datasources/analytics-datasources.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/datasources/analytics-datasources.xml
        - ${PWD}/data-analytics-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/datasources/master-datasources.xml
        - ${PWD}/data-analytics-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/tomcat/catalina-server.xml
        - ${PWD}/data-analytics-server/repository/conf/carbon.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/carbon.xml
        - ${PWD}/data-analytics-server/repository/conf/event-processor-2.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/event-processor.xml
        - ${PWD}/data-analytics-server/repository/conf/registry.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/registry.xml
        - ${PWD}/data-analytics-server/repository/conf/user-mgt.xml:/home/wso2carbon/wso2das-3.1.0/repository/conf/user-mgt.xml
        - ${PWD}/data-analytics-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2das-3.1.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
    depends_on:
      mysql:
        condition: service_healthy
    links:
        - mysql
