# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'fileutils'

# load server configurations from YAML file
CONFIGURATIONS = YAML.load_file('config.yaml')

Vagrant.configure(2) do |config|
  # loop through each server configuration specification
  CONFIGURATIONS['servers'].each do |server|
    if server['enabled'] && server['enabled'] != false
      # if the Vagrant command is effective for the server specification

      # if the deployment mode is not set
      if !CONFIGURATIONS['mode']
        puts "No deployment mode defined [The server deployment mode can only be either 'standalone' or 'cluster']"
        break
      end

      # define the virtual machine configurations
      config.vm.define server['hostname'] do |server_config|
        # define the base Vagrant box to be used
        server_config.vm.box = server['box']
        # define the virtual machine host name
        server_config.vm.host_name = server['hostname']

        # setup network configurations for the virtual machine
        if CONFIGURATIONS['mode'] == 'standalone'
          # if the virtual machine is expected to run in standalone mode (not part of a cluster)
          # port forward the defined  ports to the host machine
          server['port_mappings'].each do |port_mapping|
            if port_mapping['guest_port'] && port_mapping['host_port']
              server_config.vm.network "forwarded_port", guest: port_mapping['guest_port'], host: port_mapping['host_port'], host_ip: "127.0.0.1"
            end
          end
        elsif CONFIGURATIONS['mode'] == 'cluster'
          # if the virtual machine is expected to part of a product cluster
          # use private networking (recommended for multi-machine scenarios)
          server_config.vm.network :private_network, ip: server['ip']
        else
          # if the defined deployment mode is invalid
          puts "Incorrect deployment mode ''" + CONFIGURATIONS['mode'] + "' [The server deployment mode can only be either 'standalone' or 'cluster']"
          break
        end

        memory = server['ram'] ? server['ram'] : 2048
        cpu = server['cpu'] ? server['cpu'] : 1
        # setup VirtualBox specific provider configurations
        server_config.vm.provider :virtualbox do |vb|
          vb.name = server['hostname']
          vb.check_guest_additions = false
          vb.functional_vboxsf = false
          vb.gui = false
          vb.customize ['modifyvm', :id, '--memory', memory]
          vb.customize ['modifyvm', :id, '--cpus', cpu]
        end

        # configure shell provisioner
        if server['provisioner_script_args']
          # if argument(s) have been defined to be passed to the shell script
          server_config.vm.provision "shell", path: server["provisioner_script"], args: server["provisioner_script_args"]
        else
          # if no argument(s) have been defined to be passed to the shell script
          server_config.vm.provision "shell", path: server["provisioner_script"]
        end
      end

    end
  end
end
